'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';

export default function OpenPortalPage() {
  const [message, setMessage] = useState(''); const [created, setCreated] = useState<{ name: string; slug: string; description: string } | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const data = new FormData(event.currentTarget); const body = Object.fromEntries(data.entries()); try { const response = await fetch('/api/portals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json() as { message?: string; portal?: typeof created }; if (!response.ok || !payload.portal) { setMessage(payload.message ?? '作成できませんでした。'); return; } setCreated(payload.portal); } catch { setMessage('通信に失敗しました。'); } finally { setBusy(false); } }
  if (created) return <main className="portal-create-page"><div className="portal-complete"><p className="eyebrow">窓口ができました！</p><h1>あなたのきくまえ窓口です</h1><p>{created.name}の質問を、聞きやすく受け付けられます。</p><dl><dt>公開ページ</dt><dd><code>{typeof window !== 'undefined' ? `${window.location.origin}/${created.slug}` : `/${created.slug}`}</code></dd><dt>管理ページ</dt><dd><code>{typeof window !== 'undefined' ? `${window.location.origin}/${created.slug}/admin` : `/${created.slug}/admin`}</code></dd></dl><div className="form-actions"><Link className="button accent" href={`/${created.slug}`}>公開ページを見る</Link><Link className="button secondary" href={`/${created.slug}/admin`}>管理画面を開く</Link></div><p className="input-hint">URLを保存して、メンバーに共有してください。QRコードは次の更新で追加できます。</p></div></main>;
  return <main className="portal-create-page"><header className="site-header"><Link className="brand" href="/">🐣 きくまえ</Link><Link href="/">公開ページへ</Link></header><section className="portal-create-card"><p className="eyebrow">きくまえ窓口を開く</p><h1>あなたの場所専用の、聞きやすい窓口。</h1><p>部活・研究室・学校・会社・イベントのFAQと匿名質問ページを作れます。</p><form onSubmit={submit}><label>団体名<input name="name" required maxLength={80} placeholder="例：豊田高専ロボコン部" /></label><label>URL用の名前<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={48} placeholder="例：toyota-robocon" /><span className="input-hint">公開URL：/団体のURL用の名前</span></label><label>簡単な説明<textarea name="description" maxLength={300} placeholder="入部、見学、活動について気軽に質問できます。" /></label><label>管理者パスワード<input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password" /></label><label>パスワード（確認）<input name="passwordConfirmation" type="password" required minLength={10} maxLength={128} autoComplete="new-password" /></label><button className="button accent" type="submit" disabled={busy}>{busy ? '窓口を開いています…' : 'きくまえ窓口を開く'}</button>{message && <p className="form-status" role="status">{message}</p>}</form></section></main>;
}
